import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { Button } from "@/components/ui/button";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();

  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider signUpForceRedirectUrl="/dashboard" signInForceRedirectUrl="/dashboard" afterSignOutUrl="/">
          <header className="flex items-center justify-end gap-3 border-b px-6 py-4">
            {!userId ? (
              <>
                <SignInButton mode="modal">
                  <Button variant="ghost" size="lg">
                    Sign In
                  </Button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <Button size="lg">
                    Sign Up
                  </Button>
                </SignUpButton>
              </>
            ) : (
              <UserButton />
            )}
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
